version: '3'
services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment:
      TZ: 'Asia/Shanghai'
      MYSQL_DATABASE: 'mysql'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - mysql:/var/lib/mysql
  redis:
    image: redis:5.0.4
    container_name: redis
    restart: always
    environment:
      TZ: 'Asia/Shanghai'
    ports:
      - '6379:6379'
    expose:
      - '6379'